version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    allow:
      - dependency-name: "examples/template_pack"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    target-branch: "packlist"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    target-branch: "packlist"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3
      include:
        - "*"
