--scripts
ScriptHost:LoadScript("scripts/logic.lua")
--items
Tracker:AddItems("items/items.json")
--maps
Tracker:AddMaps("maps/maps.json")
--locations
Tracker:AddLocations("locations/locations.json")
--layouts
Tracker:AddLayouts("layouts/tracker.json")
