[binaries]
c = 'x86_64-w64-mingw32-gcc'
cpp = 'x86_64-w64-mingw32-g++'
ar = 'x86_64-w64-mingw32-ar'
windres = 'x86_64-w64-mingw32-windres'
strip = 'x86_64-w64-mingw32-strip'
pkg-config = 'x86_64-w64-mingw32-pkg-config'
# alternatively use system pkg-config and set pkg_config_libdir in [properties]
# exe_wrapper = 'wine'  # enable this if you want to run tests

[host_machine]
system = 'windows'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'

[properties]
extra_lib_dir = '/usr/x86_64-w64-mingw32/static/lib'
