#pragma once

// NOTE: the first in the list is a real release, the second is demo data

inline auto releasesData = R"""([
  {
    "url": "https://api.github.com/repos/black-sliver/PopTracker/releases/226825839",
    "assets_url": "https://api.github.com/repos/black-sliver/PopTracker/releases/226825839/assets",
    "upload_url": "https://uploads.github.com/repos/black-sliver/PopTracker/releases/226825839/assets{?name,label}",
    "html_url": "https://github.com/black-sliver/PopTracker/releases/tag/v0.32.1",
    "id": 226825839,
    "author": {
      "login": "github-actions[bot]",
      "id": 41898282,
      "node_id": "MDM6Qm90NDE4OTgyODI=",
      "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/github-actions%5Bbot%5D",
      "html_url": "https://github.com/apps/github-actions",
      "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
      "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
      "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
      "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
      "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
      "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
      "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
      "type": "Bot",
      "user_view_type": "public",
      "site_admin": false
    },
    "node_id": "RE_kwDOFPa6Ts4NhRZv",
    "tag_name": "v0.32.1",
    "target_commitish": "master",
    "name": "PopTracker v0.32.1",
    "draft": false,
    "immutable": false,
    "prerelease": false,
    "created_at": "2025-06-21T09:16:59Z",
    "updated_at": "2025-06-21T09:54:49Z",
    "published_at": "2025-06-21T09:54:49Z",
    "assets": [
      {
        "url": "https://api.github.com/repos/black-sliver/PopTracker/releases/assets/265979014",
        "id": 265979014,
        "node_id": "RA_kwDOFPa6Ts4P2oSG",
        "name": "PopTracker-0.32.1-x86_64.AppImage",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "user_view_type": "public",
          "site_admin": false
        },
        "content_type": "application/octet-stream",
        "state": "uploaded",
        "size": 53236928,
        "digest": "sha256:d1b091d6643294594499cb6d6bbfe66a9e7232b915e80bf4b4b4328f6f7ba6f4",
        "download_count": 2622,
        "created_at": "2025-06-21T09:24:25Z",
        "updated_at": "2025-06-21T09:24:27Z",
        "browser_download_url": "https://github.com/black-sliver/PopTracker/releases/download/v0.32.1/PopTracker-0.32.1-x86_64.AppImage"
      },
      {
        "url": "https://api.github.com/repos/black-sliver/PopTracker/releases/assets/265982379",
        "id": 265982379,
        "node_id": "RA_kwDOFPa6Ts4P2pGr",
        "name": "PopTracker-0.32.1-x86_64.AppImage.minisig",
        "label": null,
        "uploader": {
          "login": "black-sliver",
          "id": 59490463,
          "node_id": "MDQ6VXNlcjU5NDkwNDYz",
          "avatar_url": "https://avatars.githubusercontent.com/u/59490463?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/black-sliver",
          "html_url": "https://github.com/black-sliver",
          "followers_url": "https://api.github.com/users/black-sliver/followers",
          "following_url": "https://api.github.com/users/black-sliver/following{/other_user}",
          "gists_url": "https://api.github.com/users/black-sliver/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/black-sliver/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/black-sliver/subscriptions",
          "organizations_url": "https://api.github.com/users/black-sliver/orgs",
          "repos_url": "https://api.github.com/users/black-sliver/repos",
          "events_url": "https://api.github.com/users/black-sliver/events{/privacy}",
          "received_events_url": "https://api.github.com/users/black-sliver/received_events",
          "type": "User",
          "user_view_type": "public",
          "site_admin": false
        },
        "content_type": "application/octet-stream",
        "state": "uploaded",
        "size": 328,
        "digest": "sha256:097a02e60715a13cd3404d781f74729663bb027075997f2d44591b838f9a4434",
        "download_count": 92,
        "created_at": "2025-06-21T09:54:18Z",
        "updated_at": "2025-06-21T09:54:19Z",
        "browser_download_url": "https://github.com/black-sliver/PopTracker/releases/download/v0.32.1/PopTracker-0.32.1-x86_64.AppImage.minisig"
      },
      {
        "url": "https://api.github.com/repos/black-sliver/PopTracker/releases/assets/265978476",
        "id": 265978476,
        "node_id": "RA_kwDOFPa6Ts4P2oJs",
        "name": "poptracker_0-32-1_full-source.tar.xz",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "user_view_type": "public",
          "site_admin": false
        },
        "content_type": "application/x-xz",
        "state": "uploaded",
        "size": 3729876,
        "digest": "sha256:f2cd061ebd2fe5c3f224ba35767cc7a84f8e28117df91710d83d10ab907d98bd",
        "download_count": 245,
        "created_at": "2025-06-21T09:20:36Z",
        "updated_at": "2025-06-21T09:20:36Z",
        "browser_download_url": "https://github.com/black-sliver/PopTracker/releases/download/v0.32.1/poptracker_0-32-1_full-source.tar.xz"
      },
      {
        "url": "https://api.github.com/repos/black-sliver/PopTracker/releases/assets/265982381",
        "id": 265982381,
        "node_id": "RA_kwDOFPa6Ts4P2pGt",
        "name": "poptracker_0-32-1_full-source.tar.xz.minisig",
        "label": null,
        "uploader": {
          "login": "black-sliver",
          "id": 59490463,
          "node_id": "MDQ6VXNlcjU5NDkwNDYz",
          "avatar_url": "https://avatars.githubusercontent.com/u/59490463?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/black-sliver",
          "html_url": "https://github.com/black-sliver",
          "followers_url": "https://api.github.com/users/black-sliver/followers",
          "following_url": "https://api.github.com/users/black-sliver/following{/other_user}",
          "gists_url": "https://api.github.com/users/black-sliver/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/black-sliver/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/black-sliver/subscriptions",
          "organizations_url": "https://api.github.com/users/black-sliver/orgs",
          "repos_url": "https://api.github.com/users/black-sliver/repos",
          "events_url": "https://api.github.com/users/black-sliver/events{/privacy}",
          "received_events_url": "https://api.github.com/users/black-sliver/received_events",
          "type": "User",
          "user_view_type": "public",
          "site_admin": false
        },
        "content_type": "application/octet-stream",
        "state": "uploaded",
        "size": 331,
        "digest": "sha256:3a54b3ea8e8fe864a34ce52587201e391933c242cc55e628b487150fd4e452f9",
        "download_count": 26,
        "created_at": "2025-06-21T09:54:21Z",
        "updated_at": "2025-06-21T09:54:21Z",
        "browser_download_url": "https://github.com/black-sliver/PopTracker/releases/download/v0.32.1/poptracker_0-32-1_full-source.tar.xz.minisig"
      },
      {
        "url": "https://api.github.com/repos/black-sliver/PopTracker/releases/assets/265980230",
        "id": 265980230,
        "node_id": "RA_kwDOFPa6Ts4P2olG",
        "name": "poptracker_0-32-1_macos.zip",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "user_view_type": "public",
          "site_admin": false
        },
        "content_type": "application/zip",
        "state": "uploaded",
        "size": 6805465,
        "digest": "sha256:f7992614cf3e9a18dc92c140f55c2bc491dfe28692d3c88cc4b16a22c183cbf0",
        "download_count": 290,
        "created_at": "2025-06-21T09:34:03Z",
        "updated_at": "2025-06-21T09:34:04Z",
        "browser_download_url": "https://github.com/black-sliver/PopTracker/releases/download/v0.32.1/poptracker_0-32-1_macos.zip"
      },
      {
        "url": "https://api.github.com/repos/black-sliver/PopTracker/releases/assets/265982382",
        "id": 265982382,
        "node_id": "RA_kwDOFPa6Ts4P2pGu",
        "name": "poptracker_0-32-1_macos.zip.minisig",
        "label": null,
        "uploader": {
          "login": "black-sliver",
          "id": 59490463,
          "node_id": "MDQ6VXNlcjU5NDkwNDYz",
          "avatar_url": "https://avatars.githubusercontent.com/u/59490463?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/black-sliver",
          "html_url": "https://github.com/black-sliver",
          "followers_url": "https://api.github.com/users/black-sliver/followers",
          "following_url": "https://api.github.com/users/black-sliver/following{/other_user}",
          "gists_url": "https://api.github.com/users/black-sliver/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/black-sliver/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/black-sliver/subscriptions",
          "organizations_url": "https://api.github.com/users/black-sliver/orgs",
          "repos_url": "https://api.github.com/users/black-sliver/repos",
          "events_url": "https://api.github.com/users/black-sliver/events{/privacy}",
          "received_events_url": "https://api.github.com/users/black-sliver/received_events",
          "type": "User",
          "user_view_type": "public",
          "site_admin": false
        },
        "content_type": "application/octet-stream",
        "state": "uploaded",
        "size": 322,
        "digest": "sha256:f8193079f0a4e80bcc91825d985a8c59bdca72c5b15410f1e10c9fd4e8e09a01",
        "download_count": 25,
        "created_at": "2025-06-21T09:54:23Z",
        "updated_at": "2025-06-21T09:54:23Z",
        "browser_download_url": "https://github.com/black-sliver/PopTracker/releases/download/v0.32.1/poptracker_0-32-1_macos.zip.minisig"
      },
      {
        "url": "https://api.github.com/repos/black-sliver/PopTracker/releases/assets/265979020",
        "id": 265979020,
        "node_id": "RA_kwDOFPa6Ts4P2oSM",
        "name": "poptracker_0-32-1_ubuntu-22-04-x86_64.tar.xz",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "user_view_type": "public",
          "site_admin": false
        },
        "content_type": "application/x-xz",
        "state": "uploaded",
        "size": 1386656,
        "digest": "sha256:741db5933c4684408cbb805adaaf1edbcf74e06fd1e2126a3a2dc04aef782a92",
        "download_count": 286,
        "created_at": "2025-06-21T09:24:31Z",
        "updated_at": "2025-06-21T09:24:31Z",
        "browser_download_url": "https://github.com/black-sliver/PopTracker/releases/download/v0.32.1/poptracker_0-32-1_ubuntu-22-04-x86_64.tar.xz"
      },
      {
        "url": "https://api.github.com/repos/black-sliver/PopTracker/releases/assets/265982383",
        "id": 265982383,
        "node_id": "RA_kwDOFPa6Ts4P2pGv",
        "name": "poptracker_0-32-1_ubuntu-22-04-x86_64.tar.xz.minisig",
        "label": null,
        "uploader": {
          "login": "black-sliver",
          "id": 59490463,
          "node_id": "MDQ6VXNlcjU5NDkwNDYz",
          "avatar_url": "https://avatars.githubusercontent.com/u/59490463?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/black-sliver",
          "html_url": "https://github.com/black-sliver",
          "followers_url": "https://api.github.com/users/black-sliver/followers",
          "following_url": "https://api.github.com/users/black-sliver/following{/other_user}",
          "gists_url": "https://api.github.com/users/black-sliver/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/black-sliver/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/black-sliver/subscriptions",
          "organizations_url": "https://api.github.com/users/black-sliver/orgs",
          "repos_url": "https://api.github.com/users/black-sliver/repos",
          "events_url": "https://api.github.com/users/black-sliver/events{/privacy}",
          "received_events_url": "https://api.github.com/users/black-sliver/received_events",
          "type": "User",
          "user_view_type": "public",
          "site_admin": false
        },
        "content_type": "application/octet-stream",
        "state": "uploaded",
        "size": 339,
        "digest": "sha256:20f2e898eadf2155fe7844f1d48ea1a7e4aa250f81ea04bee87f3f41705eb46d",
        "download_count": 22,
        "created_at": "2025-06-21T09:54:24Z",
        "updated_at": "2025-06-21T09:54:25Z",
        "browser_download_url": "https://github.com/black-sliver/PopTracker/releases/download/v0.32.1/poptracker_0-32-1_ubuntu-22-04-x86_64.tar.xz.minisig"
      },
      {
        "url": "https://api.github.com/repos/black-sliver/PopTracker/releases/assets/265980235",
        "id": 265980235,
        "node_id": "RA_kwDOFPa6Ts4P2olL",
        "name": "poptracker_0-32-1_win64.zip",
        "label": "",
        "uploader": {
          "login": "github-actions[bot]",
          "id": 41898282,
          "node_id": "MDM6Qm90NDE4OTgyODI=",
          "avatar_url": "https://avatars.githubusercontent.com/in/15368?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/github-actions%5Bbot%5D",
          "html_url": "https://github.com/apps/github-actions",
          "followers_url": "https://api.github.com/users/github-actions%5Bbot%5D/followers",
          "following_url": "https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}",
          "gists_url": "https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/github-actions%5Bbot%5D/subscriptions",
          "organizations_url": "https://api.github.com/users/github-actions%5Bbot%5D/orgs",
          "repos_url": "https://api.github.com/users/github-actions%5Bbot%5D/repos",
          "events_url": "https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}",
          "received_events_url": "https://api.github.com/users/github-actions%5Bbot%5D/received_events",
          "type": "Bot",
          "user_view_type": "public",
          "site_admin": false
        },
        "content_type": "application/zip",
        "state": "uploaded",
        "size": 5884679,
        "digest": "sha256:dc6f390318be51ce7b7e8e9f13e6557c10743453fb11cc6b7cfceeda1ce8e60e",
        "download_count": 25860,
        "created_at": "2025-06-21T09:34:08Z",
        "updated_at": "2025-06-21T09:34:09Z",
        "browser_download_url": "https://github.com/black-sliver/PopTracker/releases/download/v0.32.1/poptracker_0-32-1_win64.zip"
      },
      {
        "url": "https://api.github.com/repos/black-sliver/PopTracker/releases/assets/265982416",
        "id": 265982416,
        "node_id": "RA_kwDOFPa6Ts4P2pHQ",
        "name": "poptracker_0-32-1_win64.zip.minisig",
        "label": null,
        "uploader": {
          "login": "black-sliver",
          "id": 59490463,
          "node_id": "MDQ6VXNlcjU5NDkwNDYz",
          "avatar_url": "https://avatars.githubusercontent.com/u/59490463?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/black-sliver",
          "html_url": "https://github.com/black-sliver",
          "followers_url": "https://api.github.com/users/black-sliver/followers",
          "following_url": "https://api.github.com/users/black-sliver/following{/other_user}",
          "gists_url": "https://api.github.com/users/black-sliver/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/black-sliver/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/black-sliver/subscriptions",
          "organizations_url": "https://api.github.com/users/black-sliver/orgs",
          "repos_url": "https://api.github.com/users/black-sliver/repos",
          "events_url": "https://api.github.com/users/black-sliver/events{/privacy}",
          "received_events_url": "https://api.github.com/users/black-sliver/received_events",
          "type": "User",
          "user_view_type": "public",
          "site_admin": false
        },
        "content_type": "application/octet-stream",
        "state": "uploaded",
        "size": 322,
        "digest": "sha256:4ade505c734c09943dbd126d40deae7cc2f47644a0961b1a6be927589f4d761d",
        "download_count": 259,
        "created_at": "2025-06-21T09:54:27Z",
        "updated_at": "2025-06-21T09:54:27Z",
        "browser_download_url": "https://github.com/black-sliver/PopTracker/releases/download/v0.32.1/poptracker_0-32-1_win64.zip.minisig"
      }
    ],
    "tarball_url": "https://api.github.com/repos/black-sliver/PopTracker/tarball/v0.32.1",
    "zipball_url": "https://api.github.com/repos/black-sliver/PopTracker/zipball/v0.32.1",
    "body": "This is a bugfix release.\r\n\r\nsee [CHANGELOG.md](../v0.32.1/CHANGELOG.md)\r\nand [README.md](../v0.32.1/README.md)\r\n\r\n**Important:** The AppImage seems to currently not work on some Linux distributions or requires extra dependencies. `apt install libfuse2t64` or use the Ubuntu build or build from source.\r\nDependencies to run the Ubuntu build: `apt install libssl3 libsdl2-2.0-0 libsdl2-image-2.0-0 libsdl2-ttf-2.0-0`\r\n\r\n.minisig files below are [Minisign](https://jedisct1.github.io/minisign/) signatures that can be used to verify the downloads.\r\nPublic key: `RWTTXFkF2+k6+QiNdyF96/Xmm6YcFl1Y7IhTc3lUrEhwJyf+FwBqQ/8Z` (F93AE9DB05595CD3.pub)"
  },

  {
    "url": "",
    "assets_url": "",
    "upload_url": "",
    "html_url": "https://github.com/black-sliver/PopTracker/releases/tag/v0.32.1-rc1",
    "id": 0,
    "author": {
      "login": "nobody",
      "id": 0,
      "type": "Bot"
    },
    "node_id": "",
    "tag_name": "v0.32.1-rc1",
    "target_commitish": "master",
    "name": "PopTracker v0.32.1-rc1",
    "draft": false,
    "immutable": false,
    "prerelease": true,
    "created_at": "2025-01-01T00:00:00Z",
    "updated_at": "2025-01-01T00:00:00Z",
    "published_at": "2025-01-01T00:00:00Z",
    "assets": [
    ],
    "tarball_url": "https://api.github.com/repos/black-sliver/PopTracker/tarball/v0.32.1-rc1",
    "zipball_url": "https://api.github.com/repos/black-sliver/PopTracker/zipball/v0.32.1-rc1",
    "body": ""
  }
])""";
