common_src += files(
    'poptracker.cpp',

    'ap/aptracker.cpp',
    'ap/archipelago.cpp',
    'appupdater/appupdater.cpp',
    'core/assets.cpp',
    'core/autotracker.cpp',
    'core/baseitem.cpp',
    'core/gameinfo.cpp',
    'core/imagereference.cpp',
    'core/jsonitem.cpp',
    'core/layoutclass.cpp',
    'core/layoutnode.cpp',
    'core/location.cpp',
    'core/locationsection.cpp',
    'core/log.cpp',
    'core/luaitem.cpp',
    'core/map.cpp',
    'core/pack.cpp',
    'core/scripthost.cpp',
    'core/sha256.cpp',
    'core/statemanager.cpp',
    'core/tracker.cpp',
    'core/version.cpp',
    'core/zip.cpp',
    'gh/api/release.cpp',
    'gh/api/releaseasset.cpp',
    'http/http.cpp',
    'http/httpcache.cpp',
    'http/httputil.cpp',
    'luaconnector/connection.cpp',
    'luaconnector/luaconnector.cpp',
    'luaconnector/server.cpp',
    'luasandbox/luapackio.cpp',
    'packmanager/packmanager.cpp',
    'uat/uatclient.cpp',
    'ui/broadcastwindow.cpp',
    'ui/defaulttrackerwindow.cpp',
    'ui/item.cpp',
    'ui/loadpackwidget.cpp',
    'ui/maptooltip.cpp',
    'ui/mapwidget.cpp',
    'ui/settingswindow.cpp',
    'ui/trackerview.cpp',
    'ui/trackerwindow.cpp',
    'uilib/button.cpp',
    'uilib/dlg.cpp',
    'uilib/dock.cpp',
    'uilib/drawhelper.cpp',
    'uilib/fontstore.cpp',
    'uilib/group.cpp',
    'uilib/image.cpp',
    'uilib/imagebutton.cpp',
    'uilib/imagefilter.cpp',
    'uilib/label.cpp',
    'uilib/progressbar.cpp',
    'uilib/tabs.cpp',
    'uilib/texturemanager.cpp',
    'uilib/timer.cpp',
    'uilib/tooltip.cpp',
    'uilib/ui.cpp',
    'uilib/widget.cpp',
    'uilib/window.cpp',
    'usb2snes/usb2snes.cpp',
)
