#ifndef _VERSION_H
#define _VERSION_H

#define APP_VERSION_MAJOR     0
#define APP_VERSION_MINOR    25
#define APP_VERSION_REVISION  7

#ifndef XSTR
#define XSTR(s) STR(s)
#define STR(s) #s
#endif

#define APP_VERSION_STRING XSTR(APP_VERSION_MAJOR.APP_VERSION_MINOR.APP_VERSION_REVISION)
#define APP_VERSION_TUPLE  APP_VERSION_MAJOR,APP_VERSION_MINOR,APP_VERSION_REVISION,0

#endif // _VERSION_H
