name: Codespell

on:
  push:
  pull_request:

permissions: {}

jobs:
  codespell:
    runs-on: ubuntu-latest
    name: Find typos

    steps:
    - uses: actions/checkout@v6.0.2
    - uses: codespell-project/actions-codespell@8f01853be192eb0f849a5c7d721450e7a467c579  # v2.2
      with:
        check_filenames: true
        check_hidden: true
