name: CI

on:
  push:
    branches-ignore:
      - 'screenshots'
    paths:
      - '**'
      - '!**.md'
      - '!doc/**'
      - '!schema/**'
      - '!api/lua/definition/**'
      - '!.github/workflows/**'
      - '.github/workflows/test.yaml'
  pull_request:
    branches-ignore:
      - 'screenshots'
    paths:
      - '**'
      - '!**.md'
      - '!doc/**'
      - '!schema/**'
      - '!api/lua/definition/**'
      - '!.github/workflows/**'
      - '.github/workflows/test.yaml'

permissions: {}

jobs:

  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - macos-latest  # for tests on macOS, we do regular arm and special x86_64 below
        shell: [bash]
        extra_meson_args: ['']  # default build
        include:
          - os: windows-latest
            shell: msys2 {0}
            extra_meson_args: ''
            msystem: mingw64
          #- os:  windows-11-arm  # platform detection in Makefile doesn't work currently
          #  shell: msys2 {0}
          #  extra_meson_args: ''
          #  msystem: CLANGARM64
          - os: macos-15-intel
            shell: bash
            # we now require 10.15 by default, but 10.13 should work with an extra dependency
            extra_meson_args: '-Dmacos-deplyment-target=10.13'

    name: Test ${{ matrix.os }} ${{ matrix.extra_meson_args }}
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: ${{ matrix.shell }}

    steps:
    - name: Install dependencies (apt)
      if: ${{ startsWith(matrix.os, 'ubuntu') }}
      timeout-minutes: 5
      run: |
        sudo apt-get update -y -qq
        sudo apt-get install coreutils build-essential meson \
          libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libgtest-dev libgmock-dev
    - name: Install dependencies (brew)
      if: ${{ startsWith(matrix.os, 'macos') }}
      timeout-minutes: 5
      run: |
        brew install coreutils SDL2 sdl2_ttf sdl2_image openssl@3.0 meson googletest || true
        brew link --overwrite openssl@3.0
    - name: Install extra dependencies (brew)
      if: ${{ startsWith(matrix.os, 'macos') && contains(matrix.extra_meson_args, 'macos-deplyment-target') }}
      timeout-minutes: 5
      run: |
        brew install boost || true
    - name: Install dependencies (msys2, x86_64)
      if: ${{ startsWith(matrix.os, 'windows') && !endsWith(matrix.os, 'arm')}}
      timeout-minutes: 5
      uses: msys2/setup-msys2@66cd2cce69caa17b53920067426061ca1de3a884  # v2.32.0
      with:
        msystem: ${{ matrix.msystem }}
        release: false
        update: false
        install: >-
          base-devel
          coreutils
          make
          mingw-w64-x86_64-toolchain
          mingw64/mingw-w64-x86_64-SDL2
          mingw64/mingw-w64-x86_64-SDL2_image
          mingw64/mingw-w64-x86_64-SDL2_ttf
          mingw64/mingw-w64-x86_64-freetype
          mingw64/mingw-w64-x86_64-openssl
          mingw64/mingw-w64-x86_64-gtest
          mingw64/mingw-w64-x86_64-meson
          mingw64/mingw-w64-x86_64-ntldd
          p7zip
    - name: Install dependencies (msys2, arm)
      if: ${{ startsWith(matrix.os, 'windows') && endsWith(matrix.os, 'arm')}}
      timeout-minutes: 5
      uses: msys2/setup-msys2@66cd2cce69caa17b53920067426061ca1de3a884  # v2.32.0
      with:
        msystem: ${{ matrix.msystem }}
        update: true
        install: >-
          base-devel
          coreutils
          make
          mingw-w64-clang-aarch64-toolchain
          clangarm64/mingw-w64-clang-aarch64-gcc-compat
          clangarm64/mingw-w64-clang-aarch64-SDL2
          clangarm64/mingw-w64-clang-aarch64-SDL2_image
          clangarm64/mingw-w64-clang-aarch64-SDL2_ttf
          clangarm64/mingw-w64-clang-aarch64-freetype
          clangarm64/mingw-w64-clang-aarch64-openssl
          clangarm64/mingw-w64-clang-aarch64-gtest
          clangarm64/mingw-w64-clang-aarch64-meson
          clangarm64/mingw-w64-clang-aarch64-ntldd
          p7zip
    - uses: actions/checkout@v7.0.1
      with:
        submodules: recursive
    - name: Setup env
      run: |
        echo "extra_meson_args=${{ matrix.extra_meson_args }}" >> $GITHUB_ENV
    - name: Configure ASAN (macos-latest)
      if: ${{ startsWith(matrix.os, 'macos-latest') }}
      run: |
        # see https://github.com/google/sanitizers/wiki/AddressSanitizerContainerOverflow#false-positives
        # since we don't build gtest with ASAN, we hit this issue on macos-latest
        echo "ASAN_OPTIONS=detect_container_overflow=0" >> $GITHUB_ENV
    - name: Enable ASAN and UBSAN
      # if: ${{ !startsWith(matrix.os, 'windows') }}
      if: ${{ startsWith(matrix.os, 'ubuntu') }}
      run: |
        # we use mingw on windows, which does not support ASAN
        # macos currently hangs when trying to run tests with ASAN + UBSAN on
        echo "extra_meson_args=-Db_sanitize=address,undefined ${{ env.extra_meson_args }}" >> $GITHUB_ENV
    - name: Enable UBSAN
      if: ${{ startsWith(matrix.os, 'macos') }}
      run: |
        echo "extra_meson_args=-Db_sanitize=address,undefined ${{ env.extra_meson_args }}" >> $GITHUB_ENV
    - name: Build DEBUG
      run: |
        meson setup ${{ env.extra_meson_args }} build
        meson compile -v -C build
    - name: List linked libraries (Windows)
      if: ${{ startsWith(matrix.os, 'windows') }}
      run: ntldd build/poptracker.exe  # TODO: warn if not static
    - name: List linked libraries (macos)
      if: ${{ startsWith(matrix.os, 'macos') }}
      run: otool -L build/poptracker
    - name: List linked libraries (Linux)
      if: ${{ startsWith(matrix.os, 'ubuntu') }}
      run: ldd build/poptracker
    - name: Build and run tests
      timeout-minutes: 15
      run: |
        meson test -v -C build
    - name: Store failure logs
      if: failure()
      uses: actions/upload-artifact@v7.0.1
      with:
        name: ${{ matrix.os }}_failure
        path: |
          build/meson-logs/**
          build/*.h
          build/*.json
          build/*.manifest
        if-no-files-found: ignore
        compression-level: 9

  nix-shell-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7.0.1
      with:
        submodules: recursive
    - uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24
      timeout-minutes: 5
      with:
        nix_path: nixpkgs=channel:nixos-25.05
    - run: |
        nix-shell --run 'AR=gcc-ar meson setup build && meson compile -v -C build'
    - name: Store failure logs
      if: failure()
      uses: actions/upload-artifact@v7.0.1
      with:
        name: nix_failure
        path: |
          build/meson-logs/**
          build/*.h
          build/*.json
          build/*.manifest
        if-no-files-found: ignore
        compression-level: 9
